name: Lighthouse Budget

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: '*/180 * * * *'
  repository_dispatch:
    types: lighthouse

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://hellome.ai/
            https://hellome.ai/blog/

          budgetPath: '.github/lighthouse/budget/budget.json'
          uploadArtifacts: true
          temporaryPublicStorage: true
