name: Lighthouse Desktop Config

on:
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: "*/180 * * * *"
  repository_dispatch:
    types: lighthouse

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://hellome.ai/
            https://hellome.ai/blog/

          configPath: ".github/lighthouse/custom-config/lighthouserc-desktop-config.json"
          uploadArtifacts: true
          temporaryPublicStorage: true
